name: homechef
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  flappy_search_bar:
    path: ./lib/widgets/flappy_search_bar-1.7.2-modified
  http:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

   - assets/imgs/appLogo1.png
   - assets/imgs/appLogo2.png
   - assets/imgs/appLogo3.png
   

   - assets/imgs/food1.jpg
   - assets/imgs/food2.jpg
   - assets/imgs/food3.jpg
   - assets/imgs/food4.jpg
   - assets/imgs/food5.jpg
   - assets/imgs/food6.jpg
   - assets/imgs/food7.jpg
   - assets/imgs/food8.jpg
   - assets/imgs/food9.jpg
   - assets/imgs/food10.jpg

   - assets/imgs/15min.jpg
   - assets/imgs/30min.jpg
   - assets/imgs/45min.jpg

   - assets/imgs/cuisines.jpg
   - assets/imgs/diet.jpg
   - assets/imgs/time.jpg

   - assets/imgs/glutenfree.jpg
   - assets/imgs/vegan.jpg
   - assets/imgs/vegetarian.png
   - assets/imgs/whole30.jpg
   - assets/imgs/primal.jpg
   - assets/imgs/paleo.jpeg
   - assets/imgs/pescetarian.jpg
   - assets/imgs/ovovegetarian.png
   - assets/imgs/lactovegetarian.jpg
   - assets/imgs/keto.jpg

   - assets/imgs/african.jpg
   - assets/imgs/american.jpg
   - assets/imgs/british.jpg
   - assets/imgs/cajun.jpg
   - assets/imgs/caribbean.jpg
   - assets/imgs/chinese.jpg
   - assets/imgs/easterneuropean.jpg
   - assets/imgs/european.jpg
   - assets/imgs/french.jpg
   - assets/imgs/german.jpg
   - assets/imgs/greek.jpg
   - assets/imgs/indian.jpg
   - assets/imgs/irish.jpg
   - assets/imgs/italian.jpg
   - assets/imgs/japanese.jpg
   - assets/imgs/jewish.jpg
   - assets/imgs/korean.jpg
   - assets/imgs/latinamerican.jpg
   - assets/imgs/mediterranean.jpg
   - assets/imgs/mexican.jpg
   - assets/imgs/middleeastern.jpg
   - assets/imgs/nordic.jpg
   - assets/imgs/southern.jpg
   - assets/imgs/spanish.jpg
   - assets/imgs/thai.jpg
   - assets/imgs/vietnamese.jpg

   - assets/sample_instruction_spoonacular.txt
   - assets/sample_ingredients_spoonacular.json
   - assets/sample_search_result.json

   - assets/API_KEY.txt
   - assets/API_KEY_RAPIDAPI.txt

  # fonts:
  #  - family: Roboto
  #    fonts:
  #      - asset: fonts/Roboto-Black.ttf
  #      - asset: fonts/Roboto-BlackItalic.tff
  #        style: italic
  #      - asset: fonts/Roboto-Bold.tff
  #      - asset: fonts/Roboto-BoldItalic.tff
  #        style: italic
  #      - asset: fonts/Roboto-Italic.tff
  #        style: italic
  #      - asset: fonts/Roboto-Light.tff
  #      - asset: fonts/Roboto-LightItalic.tff
  #        style: italic
  #      - asset: fonts/Roboto-Medium.tff
  #      - asset: fonts/Roboto-MediumItalic.tff
  #        style: italic
  #      - asset: fonts/Roboto-Regular.tff
  #      - asset: fonts/Roboto-Thin.tff
  #      - asset: fonts/Roboto-ThinItalic.tff
  #        style: italic
        

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Black.ttf
  #       - asset: fonts/Roboto-BlackItalic.tff
  #       - asset: fonts/Roboto-Bold.tff
  #       - asset: fonts/Roboto-BoldItalic.tff
  #       - asset: fonts/Roboto-Italic.tff
  #       - asset: fonts/Roboto-Light.tff
  #       - asset: fonts/Roboto-LightItalic.tff
  #       - asset: fonts/Roboto-Medium.tff
  #       - asset: fonts/Roboto-MediumItalic.tff
  #       - asset: fonts/Roboto-Regular.tff
  #       - asset: fonts/Roboto-Thin.tff
  #       - asset: fonts/Roboto-ThinItalic.tff
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
